### ISSUE TITLE
object java.lang.Object in compiler mirror not found

### ISSUE THREAD

**Issue by dborncamp** [DecipherNow/gm-fabric-documentation#33]
I can't build it as described. When I am on the Creating a Service/ Running the Service step 1 using the command `mvn clean generate-sources package` I cannot find the basic Java object. 

```
bash 13% mvn clean generate-sources package
[INFO] Scanning for projects...
[WARNING]
[WARNING] Some problems were encountered while building the effective model for com.example:exemplar-client:jar:0.1.0-SNAPSHOT
[WARNING] The expression ${version} is deprecated. Please use ${project.version} instead.
[WARNING]
[WARNING] Some problems were encountered while building the effective model for com.example:exemplar-server:jar:0.1.0-SNAPSHOT
[WARNING] The expression ${version} is deprecated. Please use ${project.version} instead.
[WARNING] The expression ${version} is deprecated. Please use ${project.version} instead.
[WARNING]
[WARNING] It is highly recommended to fix these problems because they threaten the stability of your build.
[WARNING]
[WARNING] For this reason, future Maven versions might no longer support building such malformed projects.
[WARNING]
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Build Order:
[INFO]
[INFO] exemplar
[INFO] exemplar-business
[INFO] exemplar-model
[INFO] exemplar-client
[INFO] exemplar-server
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building exemplar 0.1.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO]
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ exemplar ---
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building exemplar-business 0.1.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO]
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ exemplar-business ---
[INFO]
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ exemplar-business ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /Users/dborncamp/fabric-jvm/exemplar/business/src/main/resources
[INFO]
[INFO] --- scala-maven-plugin:3.1.0:add-source (scala-compile-first) @ exemplar-business ---
[INFO] Add Source directory: /Users/dborncamp/fabric-jvm/exemplar/business/src/main/scala
[INFO] Add Test Source directory: /Users/dborncamp/fabric-jvm/exemplar/business/src/test/scala
[INFO]
[INFO] --- scala-maven-plugin:3.1.0:compile (scala-compile-first) @ exemplar-business ---
[INFO] /Users/dborncamp/fabric-jvm/exemplar/business/src/main/java:-1: info: compiling
[INFO] /Users/dborncamp/fabric-jvm/exemplar/business/src/main/scala:-1: info: compiling
[INFO] Compiling 1 source files to /Users/dborncamp/fabric-jvm/exemplar/business/target/classes at 1516121060055
[ERROR] error: scala.reflect.internal.MissingRequirementError: object java.lang.Object in compiler mirror not found.
[ERROR] 	at scala.reflect.internal.MissingRequirementError$.signal(MissingRequirementError.scala:17)
[ERROR] 	at scala.reflect.internal.MissingRequirementError$.notFound(MissingRequirementError.scala:18)
[ERROR] 	at scala.reflect.internal.Mirrors$RootsBase.getModuleOrClass(Mirrors.scala:53)
[ERROR] 	at scala.reflect.internal.Mirrors$RootsBase.getModuleOrClass(Mirrors.scala:45)
[ERROR] 	at scala.reflect.internal.Mirrors$RootsBase.getModuleOrClass(Mirrors.scala:45)
[ERROR] 	at scala.reflect.internal.Mirrors$RootsBase.getModuleOrClass(Mirrors.scala:66)
[ERROR] 	at scala.reflect.internal.Mirrors$RootsBase.getClassByName(Mirrors.scala:102)
[ERROR] 	at scala.reflect.internal.Mirrors$RootsBase.getRequiredClass(Mirrors.scala:105)
[ERROR] 	at scala.reflect.internal.Definitions$DefinitionsClass.ObjectClass$lzycompute(Definitions.scala:257)
[ERROR] 	at scala.reflect.internal.Definitions$DefinitionsClass.ObjectClass(Definitions.scala:257)
[ERROR] 	at scala.reflect.internal.Definitions$DefinitionsClass.init(Definitions.scala:1394)
[ERROR] 	at scala.tools.nsc.Global$Run.<init>(Global.scala:1215)
[ERROR] 	at scala.tools.nsc.Driver.doCompile(Driver.scala:31)
[ERROR] 	at scala.tools.nsc.MainClass.doCompile(Main.scala:23)
[ERROR] 	at scala.tools.nsc.Driver.process(Driver.scala:51)
[ERROR] 	at scala.tools.nsc.Driver.main(Driver.scala:64)
[ERROR] 	at scala.tools.nsc.Main.main(Main.scala)
[ERROR] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[ERROR] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[ERROR] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[ERROR] 	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
[ERROR] 	at scala_maven_executions.MainHelper.runMain(MainHelper.java:164)
[ERROR] 	at scala_maven_executions.MainWithArgsInFile.main(MainWithArgsInFile.java:26)
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO]
[INFO] exemplar ........................................... SUCCESS [  0.147 s]
[INFO] exemplar-business .................................. FAILURE [  1.314 s]
[INFO] exemplar-model ..................................... SKIPPED
[INFO] exemplar-client .................................... SKIPPED
[INFO] exemplar-server .................................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 1.646 s
[INFO] Finished at: 2018-01-16T11:44:20-05:00
[INFO] Final Memory: 13M/46M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal net.alchim31.maven:scala-maven-plugin:3.1.0:compile (scala-compile-first) on project exemplar-business: wrap: org.apache.commons.exec.ExecuteException: Process exited with an error: 1(Exit value: 1) -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :exemplar-business
```

**Comment by dborncamp** [comment]
Turns out this was a problem with finding the incorrect version of the Java libraries. It was trying to use Java 9 when it shouldn't. I solved this by doing:

``` bash
sudo rm -fr /Library/Internet\ Plug-Ins/JavaAppletPlugin.plugin 
sudo rm -fr /Library/PreferencePanes/JavaControlPanel.prefpane
export JAVA_HOME="/Library/Java/JavaVirtualMachines/jdk1.8.0_152.jdk/Contents/Home"
```
And re-running the commands.

 Closing issue.

**Comment by joshua-rutherford** [comment]
For those reading this, it's probably safer to just set JAVA_HOME as the above `rm` commands remove somethings.

```
export JAVA_HOME=$(/usr/libexec/java_home -v 1.8)
```
